name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Fetch Upstream
      run: |
        git remote add upstream https://github.com/Rob--W/cors-anywhere.git
        git fetch upstream
        git pull upstream master

    - name: Push Changes
      run: |
        git push
